# Generated by Django 3.1.7 on 2021-03-21 14:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kvikkleire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gml_id', models.CharField(max_length=254)),
                ('lokalid', models.CharField(max_length=32)),
                ('navnerom', models.CharField(max_length=65)),
                ('versjonid', models.FloatField()),
                ('datauttaks', models.CharField(max_length=19)),
                ('datafangst', models.CharField(max_length=19)),
                ('oppdaterin', models.CharField(max_length=19)),
                ('opphav', models.CharField(max_length=43)),
                ('prosjektur', models.CharField(max_length=102)),
                ('rapporturl', models.CharField(max_length=148)),
                ('skredomrid', models.BigIntegerField()),
                ('skredomrna', models.CharField(max_length=36)),
                ('arealkm2', models.FloatField()),
                ('skredfareg', models.CharField(max_length=7)),
                ('skredskade', models.BigIntegerField()),
                ('skredrisik', models.BigIntegerField()),
                ('skredkvalk', models.BigIntegerField()),
                ('skredfar_1', models.BigIntegerField()),
                ('skredska_1', models.BigIntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
