# Generated by Django 3.1.7 on 2021-03-21 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_kvikkleire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kvikkleire',
            name='datafangst',
        ),
        migrations.RemoveField(
            model_name='kvikkleire',
            name='datauttaks',
        ),
        migrations.RemoveField(
            model_name='kvikkleire',
            name='gml_id',
        ),
        migrations.RemoveField(
            model_name='kvikkleire',
            name='lokalid',
        ),
        migrations.RemoveField(
            model_name='kvikkleire',
            name='navnerom',
        ),
        migrations.RemoveField(
            model_name='kvikkleire',
            name='oppdaterin',
        ),
        migrations.RemoveField(
            model_name='kvikkleire',
            name='opphav',
        ),
        migrations.RemoveField(
            model_name='kvikkleire',
            name='prosjektur',
        ),
        migrations.RemoveField(
            model_name='kvikkleire',
            name='rapporturl',
        ),
        migrations.RemoveField(
            model_name='kvikkleire',
            name='skredfar_1',
        ),
        migrations.RemoveField(
            model_name='kvikkleire',
            name='skredska_1',
        ),
        migrations.RemoveField(
            model_name='kvikkleire',
            name='versjonid',
        ),
    ]
